apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    release: {{ .Release.Name }}
type: Opaque
data:
  username: {{ .Values.postgres.env.user | b64enc | quote }}
  password: {{ .Values.postgres.env.password | b64enc | quote }}
